version: '3.8'
services:
  review-redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    container_name: review-redis
    
  review-mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 20020130
      MYSQL_DATABASE: reviewdb
    container_name: review-mysql