version: '3.8'
services:
  review-redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    container_name: review-redis
    
  review-mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 20020130
      MYSQL_DATABASE: reviewdb
    container_name: review-mysql

  review-consul:
    image: consul:1.15.3
    ports:
      - "8500:8500"
    container_name: review-consul
    command: >
      agent
      -server
      -bootstrap
      -ui
      -client=0.0.0.0
      -bind=0.0.0.0
    