// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameReviewInfo = "review_info"

// ReviewInfo mapped from table <review_info>
type ReviewInfo struct {
	ID             int64      `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	CreateBy       string     `gorm:"column:create_by;not null" json:"create_by"`
	UpdateBy       string     `gorm:"column:update_by;not null" json:"update_by"`
	CreateAt       time.Time  `gorm:"column:create_at;not null;default:CURRENT_TIMESTAMP" json:"create_at"`
	UpdateAt       time.Time  `gorm:"column:update_at;not null;default:CURRENT_TIMESTAMP" json:"update_at"`
	DeleteAt       *time.Time `gorm:"column:delete_at" json:"delete_at"`
	Version        int32      `gorm:"column:version;not null" json:"version"`
	ReviewID       int64      `gorm:"column:review_id;not null;comment:ID" json:"review_id"` // ID
	Content        string     `gorm:"column:content;not null" json:"content"`
	Score          int32      `gorm:"column:score;not null" json:"score"`
	ServiceScore   int32      `gorm:"column:service_score;not null" json:"service_score"`
	ExpressScore   int32      `gorm:"column:express_score;not null" json:"express_score"`
	HasMedia       int32      `gorm:"column:has_media;not null" json:"has_media"`
	OrderID        int64      `gorm:"column:order_id;not null;comment:ID" json:"order_id"` // ID
	SkuID          int64      `gorm:"column:sku_id;not null;comment:SKU ID" json:"sku_id"` // SKU ID
	SpuID          int64      `gorm:"column:spu_id;not null;comment:SPU ID" json:"spu_id"` // SPU ID
	StoreID        int64      `gorm:"column:store_id;not null;comment:ID" json:"store_id"` // ID
	UserID         int64      `gorm:"column:user_id;not null;comment:ID" json:"user_id"`   // ID
	Anonymous      int32      `gorm:"column:anonymous;not null" json:"anonymous"`
	Tags           string     `gorm:"column:tags;not null;comment:JSON" json:"tags"` // JSON
	PicInfo        string     `gorm:"column:pic_info;not null" json:"pic_info"`
	VideoInfo      string     `gorm:"column:video_info;not null" json:"video_info"`
	Status         int32      `gorm:"column:status;not null;default:10" json:"status"`
	IsDefault      int32      `gorm:"column:is_default;not null" json:"is_default"`
	HasReply       int32      `gorm:"column:has_reply;not null" json:"has_reply"`
	OpReason       string     `gorm:"column:op_reason;not null" json:"op_reason"`
	OpRemarks      string     `gorm:"column:op_remarks;not null" json:"op_remarks"`
	OpUser         string     `gorm:"column:op_user;not null" json:"op_user"`
	GoodsSnapshoot string     `gorm:"column:goods_snapshoot;not null" json:"goods_snapshoot"`
	ExtJSON        string     `gorm:"column:ext_json;not null;comment:JSON" json:"ext_json"`   // JSON
	CtrlJSON       string     `gorm:"column:ctrl_json;not null;comment:JSON" json:"ctrl_json"` // JSON
}

// TableName ReviewInfo's table name
func (*ReviewInfo) TableName() string {
	return TableNameReviewInfo
}
