// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameReviewInfo = "review_info"

// ReviewInfo 评论信息表
type ReviewInfo struct {
	ID             int64      `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                    // 主键ID
	CreateBy       string     `gorm:"column:create_by;not null;comment:创建人" json:"create_by"`                            // 创建人
	UpdateBy       string     `gorm:"column:update_by;not null;comment:更新人" json:"update_by"`                            // 更新人
	CreateAt       time.Time  `gorm:"column:create_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_at"` // 创建时间
	UpdateAt       time.Time  `gorm:"column:update_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_at"` // 更新时间
	DeleteAt       *time.Time `gorm:"column:delete_at;comment:删除时间" json:"delete_at"`                                    // 删除时间
	Version        int32      `gorm:"column:version;not null;comment:版本号" json:"version"`                                // 版本号
	ReviewID       int64      `gorm:"column:review_id;not null;comment:评论ID" json:"review_id"`                           // 评论ID
	Content        string     `gorm:"column:content;not null;comment:评论内容" json:"content"`                               // 评论内容
	Score          int32      `gorm:"column:score;not null;comment:评分" json:"score"`                                     // 评分
	ServiceScore   int32      `gorm:"column:service_score;not null;comment:服务评分" json:"service_score"`                   // 服务评分
	ExpressScore   int32      `gorm:"column:express_score;not null;comment:快递评分" json:"express_score"`                   // 快递评分
	HasMedia       int32      `gorm:"column:has_media;not null;comment:是否有媒体" json:"has_media"`                          // 是否有媒体
	OrderID        int64      `gorm:"column:order_id;not null;comment:订单ID" json:"order_id"`                             // 订单ID
	SkuID          int64      `gorm:"column:sku_id;not null;comment:SKU ID" json:"sku_id"`                               // SKU ID
	SpuID          int64      `gorm:"column:spu_id;not null;comment:SPU ID" json:"spu_id"`                               // SPU ID
	StoreID        int64      `gorm:"column:store_id;not null;comment:店铺ID" json:"store_id"`                             // 店铺ID
	UserID         int64      `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`                               // 用户ID
	Anonymous      int32      `gorm:"column:anonymous;not null;comment:是否匿名" json:"anonymous"`                           // 是否匿名
	Tags           string     `gorm:"column:tags;not null;comment:标签JSON" json:"tags"`                                   // 标签JSON
	PicInfo        string     `gorm:"column:pic_info;not null;comment:图片信息" json:"pic_info"`                             // 图片信息
	VideoInfo      string     `gorm:"column:video_info;not null;comment:视频信息" json:"video_info"`                         // 视频信息
	Status         int32      `gorm:"column:status;not null;default:10;comment:状态" json:"status"`                        // 状态
	IsDefault      int32      `gorm:"column:is_default;not null;comment:是否默认" json:"is_default"`                         // 是否默认
	HasReply       int32      `gorm:"column:has_reply;not null;comment:是否有回复" json:"has_reply"`                          // 是否有回复
	OpReason       string     `gorm:"column:op_reason;not null;comment:操作原因" json:"op_reason"`                           // 操作原因
	OpRemarks      string     `gorm:"column:op_remarks;not null;comment:操作备注" json:"op_remarks"`                         // 操作备注
	OpUser         string     `gorm:"column:op_user;not null;comment:操作用户" json:"op_user"`                               // 操作用户
	GoodsSnapshoot string     `gorm:"column:goods_snapshoot;not null;comment:商品快照" json:"goods_snapshoot"`               // 商品快照
	ExtJSON        string     `gorm:"column:ext_json;not null;comment:扩展JSON" json:"ext_json"`                           // 扩展JSON
	CtrlJSON       string     `gorm:"column:ctrl_json;not null;comment:控制JSON" json:"ctrl_json"`                         // 控制JSON
}

// TableName ReviewInfo's table name
func (*ReviewInfo) TableName() string {
	return TableNameReviewInfo
}
